arquivo = open('abastecimento.txt','r')
conteudo = arquivo.readlines()
km = input('Qual a quilometragem do veiculo na hora do abastecimento?:')
quantidade = input('Qual a quantidade de combustivel abastecido?:')
valor = input('Qual o valor pago?:')
conteudo.append('\n' + km)
conteudo.append('\n' + quantidade)
conteudo.append('\n' + valor)
arquivo = open('abastecimento.txt', 'w')
arquivo.writelines(conteudo)
arquivo.close()
